name: Test action

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  upload_to_release:
    permissions:
      # We need write permission to update the nightly tag
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Make some test file
        run: |
          echo "test string 20230606" > test-file-for-release.txt
      - name: Update nightly release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          prerelease: true
          name: 'Darktable Linux AppImage nightly build $$'
          body: |
            This is a nightly build of darktable in AppImage format.

            You can use this if you want to try new features without waiting for releases.
            From time to time, in development builds, old difficult-to-reproduce bugs are
            fixed, but it is also true that in the development process with the introduction
            of new complex code, the stability of the program may suffer compared to
            official releases, **use it with caution**!

            Also, new versions can make changes to the database schema, so it's best to run
            them with a separate library.

            Please help us improve darktable by reporting any issues you encounter. :wink:
          files: test-file-for-release.txt

      - name: Delete nightly tag
        uses: nbelingheri/delete-tag@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly

